export interface IAdminDetailsResponse {
  ID: string;
  EMAIL: string;
  FIRST_NAME: string;
  LAST_NAME: string;
  STATUS: string;
  ROLE: string;
  MOBILE: string;
  EMAIL_VERIFY: string;
  MOBILE_VERIFY: string;
  REMEMBER_TOKEN: string;
  OTHER_DETAILS: string | null;
  BANK_DETAILS: string;
  UPI_DETAILS: string;
  AMAZON_PAY: string;
  PAYTM_DETAILS: string;
  AIRTEL_MONEY_DETAILS: string;
  PHONEPE_DETAILS: string;
  LOGIN_TOKEN: string;
  WHATSAPP_NUMBER: string;
  ADMIN_DESCRIPTION: string;
  MIN_DEPOSIT: string;
  WITHDRAWAL_TIME: string;
  MIN_WITHDRAWAL: string;
  USER_BALANCE: number;
  CREATED_AT: string;
  UPDATED_AT: string;
  DEFAULT_PAYMENT: string;
  BANK_IFSC: string;
  BANK_ACCOUNT_HOLDER_NAME: string;
  BANK_BRANCH: string;
  BANK_ACCOUNT_NO: string;
  BANK_NAME: string;
  REMARKS: string;
  RAW_PASSWORD: string | null;
  AUTH_TOKEN: string | null;
  FCM_TOKEN: string;
  REFERRAL_CODE: string;
  WEB_TOKEN: string;
  LANGUAGE: string | null;
  WITHDRAWAL_LIMIT: number;
  DEVICE_SUPPORT_NUMBER: string;
  ADD_MONEY_DISABLE_MESSAGE: string;
  WITHDRAWAL_MONEY_DISABLE_MESSAGE: string;
  INACTIVE_REASON_MESSAGE: string | null;
  MAX_DEPOSIT: string;
  ADD_MONEY_ENABLE: number;
  WITHDRAW_MONEY_ENABLE: number;
  TRANSACTION_VALIDATION: number;
  UPI_DETAILS_2: string;
}
