export interface IUserDetailsResponse {
    ID: string;
    EMAIL: string;
    FIRST_NAME: string;
    LAST_NAME: string;
    STATUS: string;
    ROLE: string;
    MOBILE: string;
    EMAIL_VERIFY: string;
    MOBILE_VERIFY: string;
    REMEMBER_TOKEN: string;
    OTHER_DETAILS: string | null;
    BANK_DETAILS: string | null;
    UPI_DETAILS: string | null;
    AMAZON_PAY: string | null;
    PAYTM_DETAILS: string | null;
    AIRTEL_MONEY_DETAILS: string | null;
    PHONEPE_DETAILS: string | null;
    LOGIN_TOKEN: string | null;
    WHATSAPP_NUMBER: string | null;
    ADMIN_DESCRIPTION: string | null;
    MIN_DEPOSIT: number | null;
    WITHDRAWAL_TIME: string | null;
    MIN_WITHDRAWAL: number | null;
    USER_BALANCE: number;
    CREATED_AT: string;
    UPDATED_AT: string;
    DEFAULT_PAYMENT: string;
    BANK_IFSC: string | null;
    BANK_ACCOUNT_HOLDER_NAME: string | null;
    BANK_BRANCH: string | null;
    BANK_ACCOUNT_NO: string | null;
    BANK_NAME: string | null;
    REMARKS: string | null;
    RAW_PASSWORD: string;
    AUTH_TOKEN: string | null;
    FCM_TOKEN: string | null;
    REFERRAL_CODE: string;
    WEB_TOKEN: string | null;
    LANGUAGE: string | null;
    WITHDRAWAL_LIMIT: number;
    DEVICE_SUPPORT_NUMBER: string | null;
    ADD_MONEY_DISABLE_MESSAGE: string | null;
    WITHDRAWAL_MONEY_DISABLE_MESSAGE: string | null;
    INACTIVE_REASON_MESSAGE: string | null;
    MAX_DEPOSIT: number | null;
    ADD_MONEY_ENABLE: number;
    WITHDRAW_MONEY_ENABLE: number;
    TRANSACTION_VALIDATION: number;
    UPI_DETAILS_2: string | null;
}
