const version = 'api/v1/';
export const UriRepo = {
    LOGIN: `${version}mobileLogin?_format=json`,
    REGISTER: `${version}register?_format=json`,
    SENDOTP: `${version}sendOtp?_format=json`,
    ADMINDETAILS: `${version}adminDetails?_format=json`,
    ADDMONEY: `${version}addMoneyRequest?_format=json`,
    USERDETAILS: `${version}userDetails?_format=json`,
    UPDATEPROFILE: `${version}profileUpdate?_format=json`,
    REQUEST_OTP: `${version}forgotPasswordResendActivation?_format=json`,
    GETALLGAMECATEGORY: `${version}getAllCategory?_format=json`,
    GETGAMELISTBYCATEGORYID: `${version}getAllGame?_format=json&skip=0&take=100`,
    GETALLGAMERULES: `${version}getAllGameRules?_format=json&skip=0&take=100`,
    UPDATEFCMTOKEN: `${version}updateFcm?_format=json`,
    WITHDRAWALREQUEST: `${version}addWithdrawalRequest?_format=json`,
    REFERRALBONUS: `${version}getVariable?_format=json&name=REFERRAL_BONUS`,
    GETALLGAMETYPE: `${version}getAllGameType?_format=json`,
    PLAYGAMEMULTIPLE: `${version}playGameMultiple?_format=json`,
    TRANSACTIONLIST: (skip: number, take: number) => `${version}getAllUserTransaction?_format=json&skip=${skip}&take=${take}`,
    PLAYGAMEHISTORY: (skip: number, take: number) => `${version}getAllGameHistory?_format=json&skip=${skip}&take=${take}`,
    GETALLGAMERESULT: `${version}getAllGame?_format=json`,
    APPSTATUS: `${version}getVariable?_format=json&name=APP_STATUS`,
    GETUSERBALANCE:(userId:String)=> `${version}getUserBalance/${userId}?_format=json`,
    GETALLLANGUAGE: `language.json`,
    GETPAYMENTGATEWAY: (amount: number) => `${version}getPaymentGateway?_format=json&status=1&amount=${amount}`,
    GETKILLERPAYMENTGATEWAYDETAILS: (amount: number, id: string) => `${version}getKillerPaymentGatewayDetails?_format=json&amount=${amount}&id=${id}`,
}